name: mouse_event
description: Mouse event plugin for Flutter Desktop(Windows)
version: 0.2.0
homepage: https://github.com/rtugeek/mouse_event
repository: https://github.com/rtugeek/mouse_event
issue_tracker: https://github.com/rtugeek/mouse_event/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: MouseEventPlugin
